// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/tasks.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Left          float64                `protobuf:"fixed64,2,opt,name=left,proto3" json:"left,omitempty"`
	Right         float64                `protobuf:"fixed64,3,opt,name=right,proto3" json:"right,omitempty"`
	Operator      string                 `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Have          bool                   `protobuf:"varint,5,opt,name=have,proto3" json:"have,omitempty"`
	OpTime        uint64                 `protobuf:"varint,6,opt,name=opTime,proto3" json:"opTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskData) Reset() {
	*x = TaskData{}
	mi := &file_proto_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskData) ProtoMessage() {}

func (x *TaskData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskData.ProtoReflect.Descriptor instead.
func (*TaskData) Descriptor() ([]byte, []int) {
	return file_proto_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *TaskData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskData) GetLeft() float64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *TaskData) GetRight() float64 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *TaskData) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *TaskData) GetHave() bool {
	if x != nil {
		return x.Have
	}
	return false
}

func (x *TaskData) GetOpTime() uint64 {
	if x != nil {
		return x.OpTime
	}
	return 0
}

type TaskSubmit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result        float64                `protobuf:"fixed64,2,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSubmit) Reset() {
	*x = TaskSubmit{}
	mi := &file_proto_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSubmit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSubmit) ProtoMessage() {}

func (x *TaskSubmit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSubmit.ProtoReflect.Descriptor instead.
func (*TaskSubmit) Descriptor() ([]byte, []int) {
	return file_proto_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *TaskSubmit) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskSubmit) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TaskSubmit) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_tasks_proto_rawDescGZIP(), []int{2}
}

var File_proto_tasks_proto protoreflect.FileDescriptor

const file_proto_tasks_proto_rawDesc = "" +
	"\n" +
	"\x11proto/tasks.proto\x12\x05tasks\"\x8c\x01\n" +
	"\bTaskData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04left\x18\x02 \x01(\x01R\x04left\x12\x14\n" +
	"\x05right\x18\x03 \x01(\x01R\x05right\x12\x1a\n" +
	"\boperator\x18\x04 \x01(\tR\boperator\x12\x12\n" +
	"\x04have\x18\x05 \x01(\bR\x04have\x12\x16\n" +
	"\x06opTime\x18\x06 \x01(\x04R\x06opTime\"J\n" +
	"\n" +
	"TaskSubmit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x01R\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\a\n" +
	"\x05Empty2`\n" +
	"\x05Tasks\x12(\n" +
	"\aGetTask\x12\f.tasks.Empty\x1a\x0f.tasks.TaskData\x12-\n" +
	"\n" +
	"SubmitTask\x12\x11.tasks.TaskSubmit\x1a\f.tasks.EmptyB\x0fZ\rinternal/grpcb\x06proto3"

var (
	file_proto_tasks_proto_rawDescOnce sync.Once
	file_proto_tasks_proto_rawDescData []byte
)

func file_proto_tasks_proto_rawDescGZIP() []byte {
	file_proto_tasks_proto_rawDescOnce.Do(func() {
		file_proto_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tasks_proto_rawDesc), len(file_proto_tasks_proto_rawDesc)))
	})
	return file_proto_tasks_proto_rawDescData
}

var file_proto_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_tasks_proto_goTypes = []any{
	(*TaskData)(nil),   // 0: tasks.TaskData
	(*TaskSubmit)(nil), // 1: tasks.TaskSubmit
	(*Empty)(nil),      // 2: tasks.Empty
}
var file_proto_tasks_proto_depIdxs = []int32{
	2, // 0: tasks.Tasks.GetTask:input_type -> tasks.Empty
	1, // 1: tasks.Tasks.SubmitTask:input_type -> tasks.TaskSubmit
	0, // 2: tasks.Tasks.GetTask:output_type -> tasks.TaskData
	2, // 3: tasks.Tasks.SubmitTask:output_type -> tasks.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tasks_proto_init() }
func file_proto_tasks_proto_init() {
	if File_proto_tasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tasks_proto_rawDesc), len(file_proto_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tasks_proto_goTypes,
		DependencyIndexes: file_proto_tasks_proto_depIdxs,
		MessageInfos:      file_proto_tasks_proto_msgTypes,
	}.Build()
	File_proto_tasks_proto = out.File
	file_proto_tasks_proto_goTypes = nil
	file_proto_tasks_proto_depIdxs = nil
}
