# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tasks.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tasks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x05tasks\"S\n\x08TaskData\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04left\x18\x02 \x01(\x01\x12\r\n\x05right\x18\x03 \x01(\x01\x12\x10\n\x08operator\x18\x04 \x01(\t\x12\x0c\n\x04have\x18\x05 \x01(\x08\"(\n\nTaskSubmit\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0e\n\x06result\x18\x02 \x01(\x01\"\x07\n\x05\x45mpty2`\n\x05Tasks\x12(\n\x07GetTask\x12\x0c.tasks.Empty\x1a\x0f.tasks.TaskData\x12-\n\nSubmitTask\x12\x11.tasks.TaskSubmit\x1a\x0c.tasks.EmptyB\x0fZ\rinternal/grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rinternal/grpc'
  _globals['_TASKDATA']._serialized_start=22
  _globals['_TASKDATA']._serialized_end=105
  _globals['_TASKSUBMIT']._serialized_start=107
  _globals['_TASKSUBMIT']._serialized_end=147
  _globals['_EMPTY']._serialized_start=149
  _globals['_EMPTY']._serialized_end=156
  _globals['_TASKS']._serialized_start=158
  _globals['_TASKS']._serialized_end=254
# @@protoc_insertion_point(module_scope)
