name: Go Test
on: [push, pull_request]
jobs:
    test:
        name: Test with Coverage
        runs-on: ubuntu-latest
        steps:
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: "1.23.1"
            - name: Check out code
              uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                  go mod download
            - name: Run Unit tests
              run: |
                  go test -race -covermode atomic -coverprofile=covprofile ./...
            - name: Install goveralls
              run: go install github.com/mattn/goveralls@latest
            - name: Send coverage
              env:
                  COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: goveralls -coverprofile=covprofile -service=github -ignore cmd/app/main.go,internal/agent/agent.go,cmd/agent/main.go,internal/app/web/handlers/frontend.go,internal/app/logging/log.go,internal/app/util/util.go,internal/grpc/tasks.pb.go,internal/grpc/tasks_grpc.pb.go
